name: energycalls
host: energycalls.celesc.com.br
port: 5000
type: dockerfile

# Configuração do Build - forçar rebuild completo
build:
  dockerfile: Dockerfile
  timeout: 1800  # 30 minutos
  no_cache: true  # Forçar rebuild completo
  auto_rebuild: true  # Reconstruir automaticamente

# Configuração de Execução - usando comando direto
run:
  command: node server/server.js

# Sem health check e sem variáveis de ambiente - tudo definido no Dockerfile 