name: energycalls
host: energycalls.celesc.com.br
port: 5000
type: dockerfile

# Configuração do Build - simplificado sem args
build:
  dockerfile: Dockerfile
  timeout: 1800  # 30 minutos

# Configuração de Execução - usando comando direto
run:
  command: node server/server.js

# Sem health check e sem variáveis de ambiente - tudo definido no Dockerfile 